language: php

php:
    - 5.4
    - 5.6
    - hhvm

env:
    - SYMFONY_VERSION=2.7.*

before_script:
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-interaction --prefer-source --dev
    - composer require videlalvaro/php-amqplib:2.2.*
    - composer require react/event-loop:0.4.*
    - composer require zendframework/zend-json:2.0.*

script:
    - phpunit --coverage-text

matrix:
    include:
      - php: 5.4
        env: SYMFONY_VERSION=2.3.*

services:
  rabbitmq
