language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - AMQPLIB_VERSION=2.2.*
    - EVENTLOOP_VERSION=0.4.*

before_script:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-interaction --prefer-source --dev
    - composer require videlalvaro/php-amqplib:${AMQPLIB_VERSION}
    - composer require react/event-loop:${EVENTLOOP_VERSION}

script:
    - phpunit --coverage-text

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master
        - php: hhvm
    include:
      - php: 5.5
        env: SYMFONY_VERSION=2.4.*
      - php: 5.5
        env: SYMFONY_VERSION=2.5.*
      - php: 5.5
        env: SYMFONY_VERSION=dev-master
